name: Benchmarks
on:
  - push

jobs:
  c:
    name: C Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check gcc version
      run: gcc --version

    - name: Create build folder
      run: mkdir ${{runner.workspace}}/build

    - name: Build C
      run: gcc scripts/fibonacci.c -o ${{runner.workspace}}/build/fibonacci.x

    - name: Run script
      run: bash ${{runner.workspace}}/build/fibonacci.x
