name: Benchmarks
on:
  - push

env:
  NUMBER: 40

jobs:
  c:
    name: C Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check gcc version
      run: gcc --version

    - name: Create build folder
      run: mkdir ${{runner.workspace}}/build

    - name: Build C
      working-directory: scripts/c
      run: |
        pwd
        ls -la
        gcc fibonacci.c -o fibonacci.x
        ls -la

    - name: Run script
      working-directory: scripts/c
      run: time ./fibonacci.x $NUMBER

  python:
    name: Python Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run script
      run: python scripts/fibonacci.py $NUMBER

  php:
    name: PHP Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run script
      working-directory: scripts/php
      run: php fibonacci.php $NUMBER
